In [83]:
from datetime import datetime

def get_month_input(prompt):
    while True:
        date_str = input(prompt)
        try:
            date = datetime.strptime(date_str, '%Y-%m')
            return date
        except ValueError:
            print("Invalid format. Please enter the date in YYYY-MM format.")
print("Please enter the start and end dates in the format YYYY-MM.")
start_date = get_month_input("Enter the start month and year (YYYY-MM): ")
while True:
    end_date = get_month_input("Enter the end month and year (YYYY-MM): ")
    if end_date > start_date:
        break
    else:
        print("End date must be after the start date. Please try again.")
print(f"\nStart Date: {start_date.strftime('%Y-%m')}")
print(f"End Date: {end_date.strftime('%Y-%m')}")

Please enter the start and end dates in the format YYYY-MM.

Enter the start month and year (YYYY-MM):  1994-09
Enter the end month and year (YYYY-MM):  2024-08

Start Date: 1994-09
End Date: 2024-08

In [85]:
import pandas as pd
data = pd.read_csv('Project II Data File.csv', header = 1)
data.head()

,Unnamed: 0,SMALL LoBM,ME1 BM2,ME1 BM3,ME1 BM4,SMALL HiBM,ME2 BM1,ME2 BM2,ME2 BM3,ME2 BM4,...,ME5 BM2,ME5 BM3,ME5 BM4,BIG HiBM,Unnamed: 26,RMRF,SMB,HML,Unnamed: 30,RF
0,192607,5.8248,-1.7006,0.4875,-1.4580,2.0534,1.2077,2.4192,0.4926,-2.6049,...,6.0902,2.0266,3.1111,0.5623,NaN,2.96,-2.56,-2.43,NaN,0.22
1,192608,-2.0206,-8.0282,1.3796,1.4606,8.3968,2.3618,-1.1849,4.0084,0.5038,...,4.1903,2.0131,5.4849,7.7576,NaN,2.64,-1.17,3.82,NaN,0.25
2,192609,-4.8291,-2.6154,-4.3417,-3.2729,0.8649,-2.6540,-1.2618,1.0829,-3.5480,...,3.6538,0.0950,-0.7487,-2.4284,NaN,0.36,-1.40,0.13,NaN,0.23
3,192610,-9.3729,-3.5519,-3.4948,3.4413,-2.5476,-2.8069,-3.2663,-5.0745,-8.0191,...,-3.0071,-2.2437,-4.6719,-5.8129,NaN,-3.24,-0.09,0.70,NaN,0.32
4,192611,5.5888,4.1877,2.4623,-4.4494,0.5362,3.1033,-2.3690,3.0078,5.1546,...,2.5326,1.5204,3.6619,2.5636,NaN,2.53,-0.10,-0.51,NaN,0.31

In [87]:
cols = list(data.columns[1:])
date = list(['Date'])
data.columns = date+cols

In [89]:
data.dropna(inplace = True, axis=1)

In [91]:
# data from 1963-07 to 1993-06

data['Date'] = pd.to_datetime(data['Date'], format='%Y%m')  # Convert the 'Date' column to datetime format
data.set_index('Date', inplace=True)

In [93]:
portfolios = data.columns[:-4]

In [95]:
df = data.loc[str(start_date):str(end_date)]

In [97]:
df.shape

(360, 29)

## CAPM

In [100]:
# time series regression
import statsmodels.api as sm
import numpy as np 

results = []
residuals = pd.DataFrame(index=df.index)  # Create a DataFrame to store residuals


# Iterate through each portfolio and perform regression
for portfolio in portfolios:
    y = df[portfolio] - df['RF']  # Dependent variable: returns for each portfolio
    x = df['RMRF'] # Independent variable: market excess return (RMRF)
    
    # Add a constant (intercept) to the independent variable
    x = sm.add_constant(x)
    
    # Fit the OLS model
    model = sm.OLS(y, x).fit()

    residuals[portfolio] = y - model.fittedvalues  # y - y_pred
    
    # Extract regression results
    alpha = model.params['const']  # Intercept
    beta = model.params['RMRF']    # Coefficient (Beta)
    alpha_se = model.bse['const']  # Standard error of the intercept
    beta_se = model.bse['RMRF']    # Standard error of the beta
    exp_return = np.mean(y)
    
    # Store results in a dictionary
    results.append({
        'Portfolio': portfolio,
        'Alpha': alpha,
        'Alpha SE': alpha_se,
        'Beta': beta,
        'Beta SE': beta_se,
        'Exp_return': exp_return
    })

# Convert results into a DataFrame for better visualization
results_df = pd.DataFrame(results)
results_df.head()

    Portfolio     Alpha  Alpha SE      Beta   Beta SE  Exp_return
0  SMALL LoBM -0.733069  0.295515  1.411599  0.064488    0.333433
1     ME1 BM2 -0.061568  0.259056  1.207030  0.056532    0.850376
2     ME1 BM3 -0.010913  0.197824  1.074166  0.043169    0.800649
3     ME1 BM4  0.264413  0.204839  1.009707  0.044700    1.027275
4  SMALL HiBM  0.334630  0.239200  1.046573  0.052199    1.125344

In [102]:
# Correcting T, N, and alpha
T = df.shape[0]  # Number of time periods
N = len(portfolios)  # Number of portfolios
K = 1  # One factor in CAPM

# Demean residuals to calculate the covariance matrix
demeaned_res = residuals - np.mean(residuals, axis=0)
err_cov = np.dot(demeaned_res.T, demeaned_res) / (T - 1)

# Extract alphas from the results DataFrame
alpha = np.array(results_df['Alpha'])

# Mean and standard deviation of RMRF
mean_rmrf = np.mean(df['RMRF'])
stddev_rmrf = np.std(df['RMRF'])

# F-GRS test statistic
f_grs_p1 = ((T - N - K) / N) * (np.dot(np.dot(alpha.T, np.linalg.inv(err_cov)), alpha) / (1 + (mean_rmrf / stddev_rmrf) ** 2))

# Print the F-GRS value
print(f"F-GRS statistic: {f_grs_p1}")

F-GRS statistic: 3.8630854740794662

In [104]:
from scipy.stats import f
f_critical = f.ppf(0.95, T-N-K, N)
if f_grs_p1 > f_critical:
    print ('Alphas are jointly significantly different from zero')
else:
    print ('Alpha are not significantly different from zero')

Alphas are jointly significantly different from zero

In [106]:
#cross sectional regression

y = results_df['Exp_return']
x = results_df['Beta'] # Independent variable: market excess return (RMRF)

# Add a constant (intercept) to the independent variable
x = sm.add_constant(x)

# Fit the OLS model
model = sm.OLS(y, x).fit()

lambda_cs_capm_p1 = model.params['Beta']
lambda_cs_capm_se_p1 = model.bse['Beta']
lambda_tstat_capm_p1 = lambda_cs_capm_p1 / lambda_cs_capm_se_p1
print(f"lambda estimate and t stat for Lambda: {lambda_cs_capm_p1, lambda_tstat_capm_p1}")

lambda estimate and t stat for Lambda: (-0.4387947188334112, -1.9110617288246792)

## Fama MacBeth

In [109]:

# List to store regression coefficients (excluding intercepts)
time_step_results = []

# Iterate over each time step (i.e., each row in df_fama_time)
for i in range(df.shape[0]):
    # y: Stock returns at time step i (for all portfolios)
    y = np.array(df[portfolios].subtract(df['RF'], axis=0).iloc[[i]].T)
    
    # x: Beta values from results_df (previously calculated coefficients)
    x = np.array(results_df[['Beta']])  # Use previously calculated Betas for each portfolio
    
    # Add constant (intercept) to the independent variable
    x = sm.add_constant(x)
    
    # Fit OLS regression: y = alpha + beta * x
    model = sm.OLS(y, x).fit()
    
    # Store the coefficient (excluding intercept)
    time_step_results.append(model.params[1:])  # model.params[1:] excludes the intercept

 
# Convert the results into a DataFrame for better visualization
time_step_results_df = pd.DataFrame(time_step_results, index=df.index, columns=['lambda'])

In [110]:
mean_lambda_capm_p1_fmp = np.mean(time_step_results_df['lambda'])
std_dev_lambda_capm_p1_fmp = np.std(time_step_results_df['lambda'])/np.sqrt(T)
lambda_tstat_capm_p1_fmp = mean_lambda_capm_p1_fmp/std_dev_lambda_capm_p1_fmp
print(f"lambda estimate and t stat for Lambda: {mean_lambda_capm_p1_fmp, lambda_tstat_capm_p1_fmp}")

lambda estimate and t stat for Lambda: (-0.43879471883341115, -0.6865568531715411)

## Fama French 3 Factor

In [114]:

results = []
residuals = pd.DataFrame(index=df.index)  # Create a DataFrame to store residuals

# Iterate through each portfolio and perform regression
for portfolio in portfolios:
    y = df[portfolio] - df['RF']  # Dependent variable: excess returns for each portfolio (portfolio returns - risk-free rate)
    
    # Independent variables: Fama-French factors (RMRF, SMB, HML)
    x = df[['RMRF', 'SMB', 'HML']]  
    
    # Add a constant (intercept) to the independent variables
    x = sm.add_constant(x)
    
    # Fit the OLS model
    model = sm.OLS(y, x).fit()

    # Calculate residuals (y - y_pred)
    residuals[portfolio] = y - model.fittedvalues  
    
    # Extract regression results
    alpha = model.params['const']  # Intercept (alpha)
    beta_rmrf = model.params['RMRF']  # Coefficient for RMRF
    beta_smb = model.params['SMB']    # Coefficient for SMB
    beta_hml = model.params['HML']    # Coefficient for HML
    alpha_se = model.bse['const']     # Standard error of the intercept
    beta_rmrf_se = model.bse['RMRF']  # Standard error of the RMRF coefficient
    beta_smb_se = model.bse['SMB']    # Standard error of the SMB coefficient
    beta_hml_se = model.bse['HML']    # Standard error of the HML coefficient
    exp_return = np.mean(y)           # Expected excess return
    
    # Store results in a dictionary
    results.append({
        'Portfolio': portfolio,
        'Alpha': alpha,
        'Alpha SE': alpha_se,
        'Beta RMRF': beta_rmrf,
        'Beta RMRF SE': beta_rmrf_se,
        'Beta SMB': beta_smb,
        'Beta SMB SE': beta_smb_se,
        'Beta HML': beta_hml,
        'Beta HML SE': beta_hml_se,
        'Exp_return': exp_return
    })

# Convert results into a DataFrame for better visualization
results_df = pd.DataFrame(results)

# Display the first few rows of the results
results_df.head()

,Portfolio,Alpha,Alpha SE,Beta RMRF,Beta RMRF SE,Beta SMB,Beta SMB SE,Beta HML,Beta HML SE,Exp_return
0,SMALL LoBM,-0.582840,0.155178,1.150553,0.034871,1.410517,0.049049,-0.267979,0.046058,0.333433
1,ME1 BM2,0.046585,0.120208,0.971645,0.027013,1.348594,0.037996,-0.034767,0.035679,0.850376
2,ME1 BM3,0.021005,0.084282,0.910023,0.018940,1.062648,0.026640,0.305280,0.025016,0.800649
3,ME1 BM4,0.261375,0.077027,0.858452,0.017309,1.070382,0.024347,0.527118,0.022862,1.027275
4,SMALL HiBM,0.297880,0.129288,0.912353,0.029053,1.045504,0.040866,0.725705,0.038374,1.125344

In [116]:
# Correcting T, N, and alpha
T = df.shape[0]  # Number of time periods
N = len(portfolios)  # Number of portfolios
K = 3  

# Demean residuals to calculate the covariance matrix
demeaned_res = residuals - np.mean(residuals, axis=0)
err_cov = np.dot(demeaned_res.T, demeaned_res) / (T - 1)

factor_mu_vec = np.array(df[['RMRF', 'SMB', 'HML']])
demeaned_fac_mu = factor_mu_vec - np.mean(factor_mu_vec, axis=0)
fac_mu_cov = np.dot(demeaned_fac_mu.T, demeaned_fac_mu) / (T - 1)

# Extract alphas from the results DataFrame
alpha = np.array(results_df['Alpha'])

# F-GRS test statistic
f_grs_ff3_p1 = ((T - N - K) / N) * (np.dot(np.dot(alpha.T, np.linalg.inv(err_cov)), alpha) / (1 + np.dot(np.dot(np.mean(factor_mu_vec,axis=0), np.linalg.inv(fac_mu_cov)), np.mean(factor_mu_vec,axis=0).T)))

# Print the F-GRS value
print(f"F-GRS statistic: {f_grs_ff3_p1}")

F-GRS statistic: 3.8543498028529366

In [118]:

f_critical = f.ppf(0.95, T-N-K, N)
if f_grs_ff3_p1 > f_critical:
    print ('Alphas are jointly significantly different from zero')
else:
    print ('Alpha are not significantly different from zero')

Alphas are jointly significantly different from zero

In [120]:


# Cross-sectional regression

# y: Expected returns
y = results_df['Exp_return']

# x: Independent variables (Beta RMRF, Beta SMB, Beta HML)
x = results_df[['Beta RMRF', 'Beta SMB', 'Beta HML']]

# Add a constant (intercept) to the independent variables
x = sm.add_constant(x)

# Fit the OLS model
model = sm.OLS(y, x).fit()

# Store the coefficients (lambdas) and their standard errors
lambda_cs_ff3_p1 = model.params[['Beta RMRF', 'Beta SMB', 'Beta HML']]  # Coefficients for RMRF, SMB, HML
lambda_cs_ff3_se_p1 = model.bse[['Beta RMRF', 'Beta SMB', 'Beta HML']]  # Standard errors for RMRF, SMB, HML

# Calculate t-statistics for the coefficients (lambda estimates)
lambda_tstat_ff3_p1 = lambda_cs_ff3_p1 / lambda_cs_ff3_se_p1

# Print results
print(f"Lambda estimates: \n{lambda_cs_ff3_p1}")
print(f"\nStandard Errors: \n{lambda_cs_ff3_se_p1}")
print(f"\nT-statistics for Lambda: \n{lambda_tstat_ff3_p1}")

Lambda estimates:
Beta RMRF   -0.781531
Beta SMB     0.030811
Beta HML     0.133704
dtype: float64

Standard Errors:
Beta RMRF    0.319718
Beta SMB     0.055714
Beta HML     0.068633
dtype: float64

T-statistics for Lambda:
Beta RMRF   -2.444440
Beta SMB     0.553023
Beta HML     1.948116
dtype: float64

## Fama MacBeth

In [123]:

# List to store regression coefficients (excluding intercepts)
time_step_results = []

# Iterate over each time step (i.e., each row in df_fama_time)
for i in range(df.shape[0]):
    # y: Stock returns at time step i (for all portfolios)
    y = np.array(df[portfolios].subtract(df['RF'], axis=0).iloc[[i]].T)
    
    # x: Beta values from results_df (previously calculated coefficients)
    x = np.array(results_df[['Beta RMRF', 'Beta SMB', 'Beta HML']])  # Use previously calculated Betas for each portfolio
    
    # Add constant (intercept) to the independent variable
    x = sm.add_constant(x)
    
    # Fit OLS regression: y = alpha + beta * x
    model = sm.OLS(y, x).fit()
    
    # Store the coefficient (excluding intercept)
    time_step_results.append(model.params[1:])  # model.params[1:] excludes the intercept

 
# Convert the results into a DataFrame for better visualization
time_step_results_df = pd.DataFrame(time_step_results, index=df.index, columns=['lambda RMRF','lambda SMB','lambda HML'])

In [124]:
lambda_cs_ff3_fmp_p1 = np.mean(time_step_results_df, axis=0)
lambda_cs_ff3_se_fmp_p1 = np.std(time_step_results_df, axis=0)/np.sqrt(T)

# Calculate t-statistics for the coefficients (lambda estimates)
lambda_tstat_ff3_fmp_p1 = lambda_cs_ff3_fmp_p1 / lambda_cs_ff3_se_fmp_p1

# Print results
print(f"Lambda estimates: \n{lambda_cs_ff3_fmp_p1}")
print(f"\nStandard Errors: \n{lambda_cs_ff3_se_fmp_p1}")
print(f"\nT-statistics for Lambda: \n{lambda_tstat_ff3_fmp_p1}")

Lambda estimates:
lambda RMRF   -0.781531
lambda SMB     0.030811
lambda HML     0.133704
dtype: float64

Standard Errors:
lambda RMRF    0.423370
lambda SMB     0.177102
lambda HML     0.182601
dtype: float64

T-statistics for Lambda:
lambda RMRF   -1.845976
lambda SMB     0.173974
lambda HML     0.732220
dtype: float64

# Aggregated Results

### CAPM - CS

In [128]:


# Combine all the lists into one for easier DataFrame creation
data = {
    "Time Period": [start_date.strftime('%Y-%m') +" to "+ end_date.strftime('%Y-%m')],
    "Lambda (Î²)": [lambda_cs_capm_p1],
    "Standard Error": [lambda_cs_capm_se_p1],
    "T-Statistic": [lambda_tstat_capm_p1],
    "Significant?": ["Yes" if abs(lambda_tstat_capm_p1) > 1.96 else "No"]
}

# Create the DataFrame
df1 = pd.DataFrame(data)
df1.index = df1['Time Period']
np.round(df1.drop(columns = 'Time Period', axis=1),2)

                    Lambda (Î²)  Standard Error  T-Statistic Significant?
Time Period
1994-09 to 2024-08       -0.44            0.23        -1.91           No

### CAPM - FMP

In [130]:


# Combine all the lists into one for easier DataFrame creation
data = {
    "Time Period": [start_date.strftime('%Y-%m') +" to "+ end_date.strftime('%Y-%m')],
    "Lambda (Î²)": [mean_lambda_capm_p1_fmp],
    "Standard Error": [std_dev_lambda_capm_p1_fmp],
    "T-Statistic": [lambda_tstat_capm_p1_fmp],
    "Significant?": ["Yes" if abs(mean_lambda_capm_p1_fmp) > 1.96 else "No"]}

# Create the DataFrame
df2 = pd.DataFrame(data)
df2.index = df2['Time Period']
np.round(df2.drop(columns = 'Time Period', axis=1),2)

                    Lambda (Î²)  Standard Error  T-Statistic Significant?
Time Period
1994-09 to 2024-08       -0.44            0.64        -0.69           No

### CAPM - GRS

In [132]:
f_crit_capm = f.ppf(0.95,  N, T-N-1)

# Combine all the lists into one for easier DataFrame creation
data = {
    "Time Period": [start_date.strftime('%Y-%m') +" to "+ end_date.strftime('%Y-%m')],
    "f_grs": [f_grs_p1],
    "Critical Value": [f_crit_capm],
    "Significant?": ["Yes" if abs(f_grs_ff3_p1) > f_crit_capm else "No"]
}

# Create the DataFrame
df3 = pd.DataFrame(data)
df3.index = df3['Time Period']
np.round(df3.drop(columns = 'Time Period', axis=1),2)

                    f_grs  Critical Value Significant?
Time Period
1994-09 to 2024-08   3.86            1.54          Yes

### Fama French 3 Factor Model - CS

In [134]:

# Create the DataFrame with the relevant data
data = {
    "Time Period": [start_date.strftime('%Y-%m') +" to "+ end_date.strftime('%Y-%m')],
    "Î»_b": [lambda_cs_ff3_p1.values[0]],
    "Ïƒ(Î»_b)": [lambda_cs_ff3_se_p1.values[0]],
    "t(Î»_b)": [lambda_tstat_ff3_p1.values[0]],
    "Î»_s": [lambda_cs_ff3_p1.values[1]],
    "Ïƒ(Î»_s)": [lambda_cs_ff3_se_p1.values[1]],
    "t(Î»_s)": [lambda_tstat_ff3_p1.values[1]],
    "Î»_h": [lambda_cs_ff3_p1.values[2]],
    "Ïƒ(Î»_h)": [lambda_cs_ff3_se_p1.values[2]],
    "t(Î»_h)": [lambda_tstat_ff3_p1.values[2]]
}

# Create the DataFrame
df4 = pd.DataFrame(data)
df4.index = df4['Time Period']
np.round(df4.drop(columns = 'Time Period', axis=1),2)

,Î»_b,Ïƒ(Î»_b),t(Î»_b),Î»_s,Ïƒ(Î»_s),t(Î»_s),Î»_h,Ïƒ(Î»_h),t(Î»_h)
Time Period,,,,,,,,,
1994-09 to 2024-08,-0.78,0.32,-2.44,0.03,0.06,0.55,0.13,0.07,1.95

### Fama French 3 Factor Model - FMP

In [136]:

# Create the DataFrame with the relevant data
data = {
    "Time Period": [start_date.strftime('%Y-%m') +" to "+ end_date.strftime('%Y-%m')],
    "Î»_b": [lambda_cs_ff3_fmp_p1.values[0]],
    "Ïƒ(Î»_b)": [lambda_cs_ff3_se_fmp_p1.values[0]],
    "t(Î»_b)": [lambda_tstat_ff3_fmp_p1.values[0]],
    "Î»_s": [lambda_cs_ff3_fmp_p1.values[1]],
    "Ïƒ(Î»_s)": [lambda_cs_ff3_se_fmp_p1.values[1]],
    "t(Î»_s)": [lambda_tstat_ff3_fmp_p1.values[1]],
    "Î»_h": [lambda_cs_ff3_fmp_p1.values[2]],
    "Ïƒ(Î»_h)": [lambda_cs_ff3_se_fmp_p1.values[2]],
    "t(Î»_h)": [lambda_tstat_ff3_fmp_p1.values[2]]
}

# Create the DataFrame
df5 = pd.DataFrame(data)
df5.index = df5['Time Period']
np.round(df5.drop(columns = 'Time Period', axis=1),2)

,Î»_b,Ïƒ(Î»_b),t(Î»_b),Î»_s,Ïƒ(Î»_s),t(Î»_s),Î»_h,Ïƒ(Î»_h),t(Î»_h)
Time Period,,,,,,,,,
1994-09 to 2024-08,-0.78,0.42,-1.85,0.03,0.18,0.17,0.13,0.18,0.73

### Fama French 3 Factor Model - GRS

In [138]:
f_crit_capm = f.ppf(0.95, N,T-N-3)

# Combine all the lists into one for easier DataFrame creation
data = {
    "Time Period": [start_date.strftime('%Y-%m') +" to "+ end_date.strftime('%Y-%m')],
    "f_grs": [f_grs_ff3_p1],
    "Critical Value": [f_crit_capm],
    "Significant?": ["Yes" if abs(f_grs_ff3_p1) > f_crit_capm else "No"]
}

# Create the DataFrame
df6 = pd.DataFrame(data)
df6.index = df6['Time Period']
np.round(df6.drop(columns = 'Time Period', axis=1),2)

                    f_grs  Critical Value Significant?
Time Period
1994-09 to 2024-08   3.85            1.54          Yes